name: Check for updates and publish to Chocolatey if there are any
on:
  push:
  schedule:
    - cron: 15 23 * * *
jobs:
  package:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Make updatedPackages directory
        shell: pwsh
        run: mkdir updatedPackages
      - name: Install chocolatey-community-validation.extension
        shell: pwsh
        run: choco install chocolatey-community-validation.extension --confirm --trace --debug
      - name: Check for glab updates
        shell: pwsh
        run: ./glabUpdate.ps1
        if: always()
      - name: Check for glab.portable updates
        shell: pwsh
        run: ./glab.portableUpdate.ps1
        if: always()
      - name: Check for liftoff updates
        shell: pwsh
        run: ./liftoffUpdate.ps1
        if: always()
      - name: Check for wezterm updates
        shell: pwsh
        run: ./weztermUpdate.ps1
        if: always()
      - name: Check for wezterm.install updates
        shell: pwsh
        run: ./wezterm.installUpdate.ps1
        if: always()
      - name: Check for wezterm.portable updates
        shell: pwsh
        run: ./wezterm.portableUpdate.ps1
        if: always()
      - name: Check for floorp updates
        shell: pwsh
        run: ./floorpUpdate.ps1
        if: always()
      - name: Check for komorebi updates
        shell: pwsh
        run: ./komorebiUpdate.ps1
        if: always()
      - name: Check for whkd updates
        shell: pwsh
        run: ./whkdUpdate.ps1
        if: always()
      - name: Check for yazi updates
        shell: pwsh
        run: ./yaziUpdate.ps1
        if: always()
      - name: Check for browser-tamer updates
        shell: pwsh
        run: ./browser-tamerUpdate.ps1
        if: always()
      - name: Publish to Chocolatey
        shell: pwsh
        run: ./publishUpdates.ps1 -ApiKey ${{ secrets.PUSH_REPO_KEY }}
        if: always()
